// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:40980001337:web:5660318050a1a4f78ad3e8',
    messagingSenderId: '40980001337',
    projectId: 'watch-76784',
    authDomain: 'watch-76784.firebaseapp.com',
    storageBucket: 'watch-76784.appspot.com',
    measurementId: 'G-LWP2TELMR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:40980001337:android:7c0ede1ffaf41d5f8ad3e8',
    messagingSenderId: '40980001337',
    projectId: 'watch-76784',
    storageBucket: 'watch-76784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:40980001337:ios:d52f584850e7c8998ad3e8',
    messagingSenderId: '40980001337',
    projectId: 'watch-76784',
    storageBucket: 'watch-76784.appspot.com',
    iosBundleId: 'com.example.watch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbFkSc3qSMVWDOL7p0_nM1lzIDM-8IujY',
    appId: '1:40980001337:ios:d52f584850e7c8998ad3e8',
    messagingSenderId: '40980001337',
    projectId: 'watch-76784',
    storageBucket: 'watch-76784.appspot.com',
    iosBundleId: 'com.example.watch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOj_1CrjqE05x3jpDQgFA0_TGvHtNdCQw',
    appId: '1:40980001337:web:2d31b60492ac3e1a8ad3e8',
    messagingSenderId: '40980001337',
    projectId: 'watch-76784',
    authDomain: 'watch-76784.firebaseapp.com',
    storageBucket: 'watch-76784.appspot.com',
    measurementId: 'G-C2F5BZ84XB',
  );

}
